voices:
  teddy:
    voice: vi-VN-NamMinhNeural
    rate: "-2%"
    pitch: "+8Hz"
  lily:
    voice: vi-VN-HoaiMyNeural
    rate: "+12%"
    pitch: "+22Hz"
  hoot:
    voice: vi-VN-NamMinhNeural
    rate: "-12%"
    pitch: "-12Hz"